# Note to self: make sure pinned versions here match the versions in requirements.txt, since pre-commit has its own version of each

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2  # pin to latest stable
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/psf/black
    rev: 25.1.0  # pin to latest stable
    hooks:
      - id: black

